# Generated by Django 2.0.6 on 2018-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address_0', models.CharField(max_length=20)),
                ('address_0_code', models.CharField(max_length=2)),
                ('address_1', models.CharField(blank=True, max_length=20)),
                ('address_1_code', models.CharField(blank=True, max_length=5)),
                ('address_2', models.CharField(blank=True, max_length=20)),
                ('address_2_code', models.CharField(blank=True, max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
