# Generated by Django 2.0.6 on 2018-06-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180624_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_1_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_2_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
