# Generated by Django 2.0.6 on 2018-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_ability_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
