# Generated by Django 2.0.6 on 2018-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180616_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
