# Generated by Django 2.0.6 on 2018-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20180622_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
