# Generated by Django 2.0.6 on 2018-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20180623_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
