# Generated by Django 2.0.6 on 2018-07-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20180701_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='deleted_at',
        ),
    ]
