# Generated by Django 2.0.6 on 2018-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_image', models.URLField(max_length=500)),
                ('started_at', models.DateTimeField(blank=True)),
                ('ends_at', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
