# Generated by Django 2.0.6 on 2018-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_contact_media'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(to='common.Media'),
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ManyToManyField(to='common.Contact'),
        ),
    ]
