# Generated by Django 2.0.6 on 2018-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_ability_keyword'),
        ('project', '0002_auto_20180616_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abilities',
            field=models.ManyToManyField(to='common.Ability'),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(to='common.Keyword'),
        ),
    ]
