# Generated by Django 2.0.6 on 2018-06-17 02:34

from django.db import migrations

def forwards_func(apps, schema_editor):
    ScheduleRecurringType = apps.get_model('project', 'ScheduleRecurringType')
    db_alias = schema_editor.connection.alias
    ScheduleRecurringType.objects.using(db_alias).bulk_create([
        ScheduleRecurringType(name='매일'),
        ScheduleRecurringType(name='매주'),
        ScheduleRecurringType(name='격주'),
        ScheduleRecurringType(name='3주 마다'),
        ScheduleRecurringType(name='매달 첫주'),
        ScheduleRecurringType(name='매달 둘째 주'),
        ScheduleRecurringType(name='매달 셋째 주'),
        ScheduleRecurringType(name='매달 마지막 주'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_schedule_schedulerecurringtype'),
    ]
    

    operations = [
        migrations.RunPython(forwards_func),
    ]
