# Generated by Django 2.0.6 on 2018-06-17 04:04

from django.db import migrations

def forwards_func(apps, schema_editor):
    DescriptionQuestion = apps.get_model('project', 'DescriptionQuestion')
    db_alias = schema_editor.connection.alias
    DescriptionQuestion.objects.using(db_alias).bulk_create([
        DescriptionQuestion(question='어떤 주제를 다루는 프로젝트 인가요?'),
        DescriptionQuestion(question='어떤 사람들이 필요한지 궁금해요'),
        DescriptionQuestion(question='이 프로젝트를 한마디로 표현 한다면?'),
        DescriptionQuestion(question='자유롭게 설명해 주세요'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_descriptionquestion'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
