# Generated by Django 2.0.6 on 2018-06-17 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180617_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.DescriptionQuestion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
