# Generated by Django 2.0.6 on 2018-06-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectuserview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectdescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectuserview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schedulerecurringtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='projectdescription',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurring_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.ScheduleRecurringType'),
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.DescriptionQuestion'),
        ),
    ]
