# Generated by Django 2.0.6 on 2018-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20180617_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ends_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateField(blank=True),
        ),
    ]
