# Generated by Django 2.0.6 on 2018-06-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20180622_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='projectdescription',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.DescriptionQuestion'),
        ),
    ]
