# Generated by Django 2.0.6 on 2018-06-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180623_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Schedule'),
            preserve_default=False,
        ),
    ]
