# Generated by Django 2.0.6 on 2018-06-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20180624_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Schedule'),
        ),
    ]
