# Generated by Django 2.0.6 on 2018-06-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180624_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='schedule',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.Schedule'),
            preserve_default=False,
        ),
    ]
