# Generated by Django 2.0.6 on 2018-06-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180624_1407'),
        ('project', '0017_auto_20180624_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.Location'),
            preserve_default=False,
        ),
    ]
