# Generated by Django 2.0.6 on 2018-07-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
