# Generated by Django 2.0.6 on 2018-08-05 02:35

import base.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20180730_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmemberrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='projectmemberrequest',
            name='status',
            field=models.CharField(choices=[(base.enums.RequestStatus('Requested'), 'Requested'), (base.enums.RequestStatus('Accepted'), 'Accepted'), (base.enums.RequestStatus('Rejected'), 'Rejected')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
