# Generated by Django 2.0.6 on 2018-08-05 02:40

import base.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20180805_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberrequest',
            name='status',
            field=models.CharField(choices=[(base.enums.RequestStatus('Requested'), 'Requested'), (base.enums.RequestStatus('Accepted'), 'Accepted'), (base.enums.RequestStatus('Rejected'), 'Rejected')], max_length=100),
        ),
    ]
