# Generated by Django 2.0.6 on 2018-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20180805_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmemberrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=10),
        ),
    ]
