# Generated by Django 2.0.6 on 2018-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20180805_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'owner'), ('ADMIN', 'admin'), ('MEMBER', 'member')], max_length=10),
        ),
    ]
