# Generated by Django 2.0.6 on 2018-06-16 08:05
from __future__ import unicode_literals
from django.db import migrations
from user.models import User

def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_admin = True
    superuser.has_terms = True
    superuser.has_privacy_policy = True
    superuser.username = 'admin'
    superuser.email = 'admin@sandwhichi.com'
    superuser.set_password('Cucumber21818!')
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
