# Generated by Django 2.0.6 on 2018-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20180706_2327'),
        ('user', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='abilities',
            field=models.ManyToManyField(to='common.Ability'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_certified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keywords',
            field=models.ManyToManyField(to='common.Keyword'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
