# Generated by Django 2.0.6 on 2018-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_create_superuser_20180616_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
